name: nixbuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19 # https://github.com/cachix/install-nix-action/releases/tag/v19
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - name: Print nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Building Nix package
      run: nix-build --attr app -- --no-out-link
